<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Transaksi {{ \Carbon\Carbon::now()->format('F Y') }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        html, body {
            height: 100%;
            width: 100%;
        }
        body {
            font-family: 'Arial', sans-serif;
            font-size: 14px;
            line-height: 1.6;
            color: #333;
            display: flex;
            flex-direction: column;
        }
        header {
            text-align: center;
            color: #fff;
            background: linear-gradient(135deg, #f7a600, #f0c000); /* Gradasi kuning oranye */
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        header h1 {
            font-size: 24px;
            margin: 0;
            color: #f7a600;
        }
        header h2 {
            font-size: 18px;
            margin: 5px 0;
            color: #f7a600;
        }
        header p {
            font-size: 14px;
            margin: 5px 0 0;
            color: #f7a600;
        }
        .content {
            flex: 1;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            background-color: #fff;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f7a600; /* Kuning oranye utama */
            color: #fff;
            text-transform: uppercase;
            font-size: 12px;
        }
        tr:nth-child(even) {
            background-color: #fff2d1; /* Kuning lembut */
        }
        tr:nth-child(odd) {
            background-color: #fff8e5; /* Kuning sangat lembut */
        }
        tfoot td {
            font-weight: bold;
            text-align: right;
            background-color: #ffe5a3; /* Kuning terang */
            color: #333;
        }
        tfoot td:first-child {
            text-align: left;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #555;
            padding: 10px;
            background-color: #f7a600; /* Kuning oranye */
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="kop-surat">
            <h1>{{ $perpustakaan->nama_perpustakaan }}</h1>
            <h2>{{ $perpustakaan->alamat }}</h2>
            <p>Telepon: {{ $perpustakaan->no_telp }} | Email: {{ $perpustakaan->email }}</p>
        </div>        
    </header>
    <div class="content">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Anggota</th>
                    <th>Judul Buku</th>
                    <th>Tanggal Pinjam</th>
                    <th>Tanggal Kembali</th>
                    <th>Denda</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($laporan as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->anggota->nama_anggota }}</td>
                    <td>{{ $item->pustaka->judul_pustaka }}</td>
                    <td>{{ $item->tgl_pinjam }}</td>
                    <td>{{ $item->tgl_pengembalian }}</td>
                    <td>Rp.{{ number_format($item->denda) }}</td>
                    <td>
                        @if($item->fp == '1')
                            Dikembalikan
                        @elseif($item->fp == '2')
                            Hilang
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Total Transaksi</td>
                    <td>{{ count($laporan) }}</td>
                </tr>
                <tr>
                    <td colspan="6">Total Denda</td>
                    <td>Rp.{{ number_format($laporan->sum('denda')) }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="footer">
        <p>Generated by System | {{ \Carbon\Carbon::now()->format('d-m-Y H:i:s') }}</p>
    </div>
</body>
</html>
